micronaut:
  application:
    name: micronautKafka
netty:
  default:
    allocator:
      max-order: 3

kafka:
  embedded:
    enabled: true
  bootstrap:
    servers: localhost:9092
  specific:
    avro:
      reader: true
  schema:
    registry:
      url: http://localhost:8090/apis/registry/v2

  apicurio:
    registry:
      artifact-resolver-strategy: io.apicurio.registry.serde.strategy.TopicIdStrategy
      headers:
        enabled: true
      find-latest: true
      auto-register: true
      use-specific-avro-reader: true
      url: http://localhost:8090/apis/registry/v2
  consumers:
    avro:
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
  producers:
    avro:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer


